import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { sourceFiles } from './src/source-files.mjs';

const directory = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const Babel = require(path.join(directory, 'vendor/babel.js'));
const lucide = require(path.join(directory, 'vendor/lucide.js'));
const [template, ...sourceParts] = await Promise.all([
  readFile(path.join(directory, 'src/template.html'), 'utf8'),
  ...sourceFiles.map(sourceFile => readFile(path.join(directory, 'src', sourceFile), 'utf8'))
]);
// 用函数式替换：源码里含 `$&`（正则转义辅助）时，字符串替换会把它当成"整段匹配"模式而写坏产物。
const source = `<!-- Generated by build.mjs. Edit files under src/ instead. -->\n${template.replace('/* MOREIMG_SOURCE */', () => sourceParts.join('\n'))}`;
const scriptPattern = /\s*<script type="text\/babel">([\s\S]*?)<\/script>/;
const match = source.match(scriptPattern);

if (!match) {
  throw new Error('src.html 中未找到 text/babel 应用脚本');
}

// 图标名写错时旧逻辑只是静默跳过：产物少一个图标，构建照样成功，页面渲染成空 svg。
// 这里把字面量图标名收集与校验分开，拼错立即让构建失败。
const referencedIconNames = new Set();
for (const iconTag of source.match(/<Icon\b[\s\S]*?\/>/g) || []) {
  // 只看 name= 属性，避免把 className 等属性里的大写词误当图标名。
  const nameAttribute = iconTag.match(/\bname=("[^"]*"|\{[^{}]*\})/);
  if (!nameAttribute) continue;
  for (const stringMatch of nameAttribute[1].matchAll(/['"]([A-Z][A-Za-z0-9]*)['"]/g)) {
    referencedIconNames.add(stringMatch[1]);
  }
}
for (const iconMatch of source.matchAll(/\bicon:\s*['"]([A-Z][A-Za-z0-9]*)['"]/g)) {
  referencedIconNames.add(iconMatch[1]);
}

const unknownIconNames = [...referencedIconNames].filter(name => !lucide.icons[name]).sort();
if (unknownIconNames.length > 0) {
  throw new Error(`Lucide 中不存在这些图标名：${unknownIconNames.join('、')}。请检查拼写（图标名区分大小写）。`);
}

const iconNames = referencedIconNames;

const iconSubset = Object.fromEntries([...iconNames].sort().map(name => [name, lucide.icons[name][2]]));
const iconBundle = `/* Lucide icon subset, ISC License: https://lucide.dev/license */\nwindow.moreimgIcons=Object.freeze(${JSON.stringify(iconSubset)});\n`;
const iconVersion = createHash('sha256').update(iconBundle).digest('hex').slice(0, 12);

const assetPaths = [
  'styles.css',
  'vendor/react.js',
  'vendor/react-dom.js',
  'vendor/html2canvas.js',
  'fonts/noto-sans-sc.css'
];
const assetContents = Object.fromEntries(await Promise.all(assetPaths.map(async assetPath => [
  assetPath,
  await readFile(path.join(directory, assetPath))
])));
const assetVersions = Object.fromEntries(assetPaths.map(assetPath => [
  assetPath,
  createHash('sha256').update(assetContents[assetPath]).digest('hex').slice(0, 12)
]));

// 缓存失效与 Babel 剥离都依赖"目标字符串恰好出现一次"。
// 一条提到同名路径的注释就能让非全局 replace 换错位置且构建仍然成功，因此这里强制断言命中次数。
const replaceOnce = (input, target, replacement, description) => {
  const matches = input.match(target instanceof RegExp ? new RegExp(target.source, `${target.flags.replace('g', '')}g`) : new RegExp(target.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'));
  const count = matches ? matches.length : 0;
  if (count !== 1) {
    throw new Error(`${description} 期望恰好命中 1 处，实际 ${count} 处。请检查是否有同名注释或重复引用。`);
  }
  return input.replace(target, () => replacement);
};

// 没有 targets 时 preset-env 会一路降级到 ES5，凭空多出三成体积；
// 而源码本来就直接用 AbortController / Object.fromEntries / Array.prototype.at 且不带 polyfill，
// 所谓的 ES5 兼容从来不成立。这里对齐真实支持面：近两年的主流浏览器。
const browserTargets = { chrome: '109', edge: '109', firefox: '115', safari: '16.4' };

const { code: transformedCode } = Babel.transform(match[1], {
  presets: [['env', { modules: false, targets: browserTargets }], ['react', { runtime: 'classic' }]],
  comments: false,
  compact: false,
  sourceType: 'script',
});
const code = [
  ['vendor/html2canvas.js', `vendor/html2canvas.js?v=${assetVersions['vendor/html2canvas.js']}`],
  ['fonts/noto-sans-sc.css', `fonts/noto-sans-sc.css?v=${assetVersions['fonts/noto-sans-sc.css']}`]
].reduce((current, [assetPath, versioned]) => replaceOnce(current, assetPath, versioned, `app.js 中的 ${assetPath}`), transformedCode);
const appVersion = createHash('sha256').update(code).digest('hex').slice(0, 12);

let html = replaceOnce(
  source,
  /\s*<!-- Babel -->\s*<script src="vendor\/babel\.js"><\/script>/,
  '',
  '生产页的 Babel 标签剥离'
);
html = replaceOnce(html, scriptPattern, `\n  <script src="app.js?v=${appVersion}" defer></script>`, 'text/babel 应用脚本替换');

for (const assetPath of ['styles.css', 'vendor/react.js', 'vendor/react-dom.js', 'vendor/lucide-moreimg.js']) {
  const version = assetPath === 'vendor/lucide-moreimg.js' ? iconVersion : assetVersions[assetPath];
  html = replaceOnce(html, assetPath, `${assetPath}?v=${version}`, `index.html 中的 ${assetPath}`);
}

await Promise.all([
  writeFile(path.join(directory, 'src.html'), source),
  writeFile(path.join(directory, 'app.js'), `/* Generated by build.mjs. Edit files under src/ instead. */\n${code}\n`),
  writeFile(path.join(directory, 'index.html'), html),
  writeFile(path.join(directory, 'vendor/lucide-moreimg.js'), iconBundle),
]);

console.log(`Built moreimg/src.html, index.html, app.js and ${iconNames.size} Lucide icons from ${sourceFiles.length} modules`);
