import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sourceFiles } from '../src/source-files.mjs';

const projectDirectory = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const [template, generatedSource, ...sourceParts] = await Promise.all([
  readFile(path.join(projectDirectory, 'src/template.html'), 'utf8'),
  readFile(path.join(projectDirectory, 'src.html'), 'utf8'),
  ...sourceFiles.map(sourceFile => readFile(path.join(projectDirectory, 'src', sourceFile), 'utf8'))
]);
const expectedSource = `<!-- Generated by build.mjs. Edit files under src/ instead. -->\n${template.replace('/* MOREIMG_SOURCE */', sourceParts.join('\n'))}`;

assert.equal(generatedSource, expectedSource, 'src/ 变化后必须运行 node build.mjs 更新聚合源码');
assert.equal(new Set(sourceFiles).size, sourceFiles.length, '源码清单不得包含重复模块');

console.log('Modular source files and generated src.html are synchronized.');
