import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sourceFiles } from '../src/source-files.mjs';

const projectDirectory = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const [template, generatedSource, ...sourceParts] = await Promise.all([
  readFile(path.join(projectDirectory, 'src/template.html'), 'utf8'),
  readFile(path.join(projectDirectory, 'src.html'), 'utf8'),
  ...sourceFiles.map(sourceFile => readFile(path.join(projectDirectory, 'src', sourceFile), 'utf8'))
]);
// 用 split 而非 replace 拼装期望值：replace 的替换串会解析 `$&` 等模式，
// 与 build.mjs 犯同一个错时这条断言会一起失明。
const marker = '/* MOREIMG_SOURCE */';
const templateParts = template.split(marker);
assert.equal(templateParts.length, 2, `src/template.html 必须恰好包含一处 ${marker}`);
const expectedSource = `<!-- Generated by build.mjs. Edit files under src/ instead. -->\n${templateParts[0]}${sourceParts.join('\n')}${templateParts[1]}`;

assert.equal(generatedSource, expectedSource, 'src/ 变化后必须运行 node build.mjs 更新聚合源码');
assert.equal(new Set(sourceFiles).size, sourceFiles.length, '源码清单不得包含重复模块');
assert.ok(!generatedSource.includes(marker), '聚合产物中不应残留源码占位标记');

console.log('Modular source files and generated src.html are synchronized.');
